import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/Redux/Providers";
import { ThemeProvider } from "next-themes";
import AOSInit from "@/utils/AOSInit";
import ScrollToTop from "@/utils/scrollToTop";
import Header from "@/components/header/header";
import { getMe } from "@/utils/getMe";
require("dotenv").config();

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: " پژوهشسرای باقرالعلوم | ناحیه یک ارومیه",
  description: "Generated by create next app",
  icons: "/img/logo.webp"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getMe();
  console.log("user : ", user);
  return (
    <Providers>
      <html lang='en' dir='rtl' suppressHydrationWarning={true}>
        <body className={`${inter.className} relative`}>
          <ThemeProvider attribute='class'>
          {/* <div className=' flex justify-center h-full sticky top-0 z-50'>
              <Header user={JSON.parse(JSON.stringify(user))} />
            </div> */}
            <AOSInit />
            {children}
          </ThemeProvider>
          <div className='fixed bottom-4 left-4  '>
            <ScrollToTop />
          </div>
        </body>
      </html>
    </Providers>
  );
}
