import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { ThemeProvider } from "next-themes";
import store from "./../../Redux/Store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' dir='rtl'>
      <body className={inter.className}>
        {/* <Provider store={store}> */}
          <ThemeProvider attribute='class'>{children}</ThemeProvider>
        {/* </Provider> */}
      </body>
    </html>
  );
}
